# Generated by Django 2.2.28 on 2023-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neo4j', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Page_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('main_title', models.TextField()),
                ('img1', models.ImageField(upload_to='img/%y')),
                ('img2', models.ImageField(upload_to='img/%y')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('explin1', models.TextField()),
                ('explin2', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Main_Page_Content',
            },
        ),
    ]
