# Generated by Django 2.2.28 on 2023-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neo4j', '0002_main_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/%y')),
                ('Maintxt1', models.TextField()),
                ('Maintxt2', models.TextField()),
                ('p1', models.CharField(max_length=150)),
                ('p2', models.CharField(max_length=150)),
                ('p3', models.CharField(max_length=150)),
                ('p4', models.CharField(max_length=150)),
                ('p5', models.CharField(max_length=150)),
                ('p6', models.CharField(max_length=150)),
                ('txt1', models.TextField()),
                ('txt2', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
